# Generated by Django 3.1 on 2021-07-17 15:03

import cloudinary.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(null=True)),
                ('profile_photo', cloudinary.models.CloudinaryField(max_length=255, null=True, verbose_name='profile_photo')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('project_image', cloudinary.models.CloudinaryField(max_length=255, null=True, verbose_name='project_image')),
                ('pub_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('description', models.TextField()),
                ('link', models.CharField(max_length=255, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('porf_ref', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='awwards.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.TextField()),
                ('rate_design', models.PositiveSmallIntegerField(choices=[(1, '1 - awful2'), (2, '2 - Horrible'), (3, '3 - Terrible'), (4, '4 - Bad'), (5, '5 - OK'), (6, '6 - nice work'), (7, '7 - Good'), (8, '8 - Very Good'), (9, '9 - Perfect'), (10, '10 - Masterpiece')], null=True)),
                ('rate_usability', models.PositiveSmallIntegerField(choices=[(1, '1 - awful2'), (2, '2 - Horrible'), (3, '3 - Terrible'), (4, '4 - Bad'), (5, '5 - OK'), (6, '6 - nice work'), (7, '7 - Good'), (8, '8 - Very Good'), (9, '9 - Perfect'), (10, '10 - Masterpiece')], null=True)),
                ('rate_content', models.PositiveSmallIntegerField(choices=[(1, '1 - awful2'), (2, '2 - Horrible'), (3, '3 - Terrible'), (4, '4 - Bad'), (5, '5 - OK'), (6, '6 - nice work'), (7, '7 - Good'), (8, '8 - Very Good'), (9, '9 - Perfect'), (10, '10 - Masterpiece')], null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='awwards.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
