# Generated by Django 3.1.2 on 2020-10-23 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('awwardsapp', '0004_project_link'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='user',
            new_name='user_ref',
        ),
    ]
