# Generated by Django 3.1.2 on 2020-10-24 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('awwardsapp', '0005_auto_20201023_2149'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='user_ref',
            new_name='prof_ref',
        ),
    ]
